version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RWS_APPLICATION_ID: $RWS_APPLICATION_ID
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password