version: 2.1
jobs:
  rspec:
    working_directory: ~/app
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
            echo RWS_APPLICATION_ID=${RWS_APPLICATION_ID} > ~/.env
            echo RWS_AFFILIATION_ID=${RWS_AFFILIATION_ID} > ~/.env
      - run:
          name: Start containers and verify it is working
          command: |
            set -x
            docker-compose up -d
            docker exec app_app_1 curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
      - run:
          name: Setup database
          command: |
            docker-compose exec app rails db:create
      - run:
          name: Run rspec
          command: docker-compose exec app rspec

  rubocop:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:3.0.2
    steps:
      - checkout
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  heroku_deploy:
    working_directory: ~/app
    docker:
      - image: sue445/heroku-cli
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Identify who I am
          command: echo 'export MY_EMAIL=`heroku auth:whoami | tail -n 1`' >> $BASH_ENV
      - run:
          name: Define Heroku app name to create
          command: echo "export HEROKU_APP_NAME=portfolio-temma" >> $BASH_ENV
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - heroku_deploy:
          requires:
            - rspec
            - rubocop